from __future__ import annotations

import html

from ciburn.audit import AuditResult
from ciburn.findings import Finding
from ciburn.report.common import (
    headline,
    money,
    observed_cell,
    recoverable_cell,
    top_groups,
    totals_lines,
)

CSS = """
body{font:14px/1.45 system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem;color:#1a1a1a;background:#fff}
h1{font-size:1.25rem}h2{font-size:1.05rem;margin-top:2rem}table{border-collapse:collapse;width:100%;margin:.5rem 0}
th,td{border:1px solid #ddd;padding:.35rem .5rem;text-align:left;vertical-align:top}th{background:#f3f3f3}
td.num{text-align:right;white-space:nowrap}.sev-high{color:#b00020;font-weight:600}.sev-medium{color:#8a6d00}
.sev-low{color:#005f73}.method{color:#666;font-size:.9em}.fix{color:#1b5e20}.note{color:#666}
.measured th{background:#e8f5e9}.advisory th{background:#fff8e1}
"""


def _e(s: object) -> str:
    return html.escape(str(s))


def _where(f: Finding) -> str:
    wf = (f.workflow or "").removeprefix(".github/workflows/")
    return f"{wf}#{f.job}" if f.job else wf or "(repo)"


def render_html(result: AuditResult, *, max_rows: int = 60) -> str:
    parts = [
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>",
        f"<title>ciburn report — {_e(result.repo or result.path or '')}</title><style>{CSS}</style></head><body>",
        f"<h1>{_e(headline(result))}</h1>",
    ]
    if result.error:
        parts.append(f"<p class='sev-high'>error: {_e(result.error)}</p>")
    parts.append(
        "<ul>" + "".join(f"<li>{_e(line)}</li>" for line in totals_lines(result)) + "</ul>"
    )
    groups = top_groups(result)
    if groups:
        parts.append(
            "<h2>Where the minutes go</h2><table><tr><th>workflow</th><th>job</th><th>jobs</th><th>billed min</th><th>list price</th><th>p50 min</th></tr>"
        )
        for path, base, n, mins, cost, p50 in groups:
            parts.append(
                f"<tr><td>{_e(path.removeprefix('.github/workflows/'))}</td><td>{_e(base)}</td><td class='num'>{n}</td>"
                f"<td class='num'>{mins:,}</td><td class='num'>{_e(money(cost))}</td><td class='num'>{p50:.1f}</td></tr>"
            )
        parts.append("</table>")
    measured = result.measured
    parts.append(
        f"<h2>Measured findings ({len(measured)}) — from this repository's run history</h2>"
    )
    if measured:
        parts.append(
            "<table class='measured'><tr><th>rule</th><th>sev</th><th>where</th><th>observed</th><th>recoverable (estimate)</th><th>conf</th><th>finding</th></tr>"
        )
        for f in measured[:max_rows]:
            parts.append(
                f"<tr><td>{f.rule_id}</td><td class='sev-{f.severity.value}'>{f.severity.value}</td><td>{_e(_where(f))}</td>"
                f"<td>{_e(observed_cell(f))}</td><td>{_e(recoverable_cell(f, result))}</td><td>{f.confidence.value}</td>"
                f"<td>{_e(f.message)}<br><span class='fix'>fix: {_e(f.remediation.summary)}</span>"
                + (
                    f"<br><span class='method'>method: {_e(f.estimate_method)}</span>"
                    if f.estimate_method
                    else ""
                )
                + "</td></tr>"
            )
        parts.append("</table>")
    else:
        parts.append("<p>None.</p>")
    advisory = result.advisory
    parts.append(
        f"<h2>Advisory findings ({len(advisory)}) — configuration only, no history evidence</h2>"
    )
    if advisory:
        parts.append(
            "<table class='advisory'><tr><th>rule</th><th>sev</th><th>where</th><th>finding</th><th>fix</th></tr>"
        )
        for f in advisory[:max_rows]:
            parts.append(
                f"<tr><td>{f.rule_id}</td><td class='sev-{f.severity.value}'>{f.severity.value}</td><td>{_e(_where(f))}</td>"
                f"<td>{_e(f.message)}</td><td>{_e(f.remediation.summary)}</td></tr>"
            )
        parts.append("</table>")
    else:
        parts.append("<p>None.</p>")
    if result.notes:
        parts.append(
            "<h2>Notes</h2><ul class='note'>"
            + "".join(f"<li>{_e(n)}</li>" for n in result.notes)
            + "</ul>"
        )
    parts.append(
        f"<p class='note'>Estimates are labelled; each carries its method. Rates: <a href='{_e(result.model.source_url)}'>"
        f"{_e(result.model.source_url)}</a> (fetched {result.pricing.fetched_at:%Y-%m-%d}). Generated by ciburn.</p></body></html>"
    )
    return "\n".join(parts) + "\n"
