from __future__ import annotations

from ciburn.audit import AuditResult
from ciburn.findings import Finding
from ciburn.report.common import (
    headline,
    money,
    observed_cell,
    recoverable_cell,
    top_groups,
    totals_lines,
)


def _esc(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def render_markdown(result: AuditResult, *, max_rows: int = 40) -> str:
    out: list[str] = [f"## {headline(result)}", ""]
    if result.error:
        out += [f"> **error:** {result.error}", ""]
    out += [f"- {line}" for line in totals_lines(result)]
    out.append("")
    groups = top_groups(result)
    if groups:
        out += [
            "### Where the minutes go",
            "",
            "| workflow | job | jobs | billed min | list price | p50 min |",
            "|---|---|---:|---:|---:|---:|",
        ]
        for path, base, n, mins, cost, p50 in groups:
            out.append(
                f"| {_esc(path.removeprefix('.github/workflows/'))} | {_esc(base)} | {n} | {mins:,} | {money(cost)} | {p50:.1f} |"
            )
        out.append("")
    measured = result.measured
    out.append(f"### Measured findings ({len(measured)}) — from this repository's run history")
    out.append("")
    if measured:
        out += [
            "| rule | sev | where | observed | recoverable (estimate) | conf | finding |",
            "|---|---|---|---|---|---|---|",
        ]
        for f in measured[:max_rows]:
            out.append(
                f"| {f.rule_id} | {f.severity.value} | {_esc(_where(f))} | {_esc(observed_cell(f))} | "
                f"{_esc(recoverable_cell(f, result))} | {f.confidence.value} | {_esc(f.message)} "
                f"**Fix:** {_esc(f.remediation.summary)}"
                + (f" _Method: {_esc(f.estimate_method)}_" if f.estimate_method else "")
                + " |"
            )
    else:
        out.append("_None._")
    out.append("")
    advisory = result.advisory
    out.append(f"### Advisory findings ({len(advisory)}) — configuration only, no history evidence")
    out.append("")
    if advisory:
        out += ["| rule | sev | where | finding | fix |", "|---|---|---|---|---|"]
        for f in advisory[:max_rows]:
            out.append(
                f"| {f.rule_id} | {f.severity.value} | {_esc(_where(f))} | {_esc(f.message)} | {_esc(f.remediation.summary)} |"
            )
    else:
        out.append("_None._")
    out.append("")
    if result.notes:
        out += (
            ["<details><summary>Notes</summary>", ""]
            + [f"- {n}" for n in result.notes]
            + ["", "</details>", ""]
        )
    out.append(
        f"<sub>Estimates are labelled; each carries its method. Rates: {result.model.source_url} "
        f"(fetched {result.pricing.fetched_at:%Y-%m-%d}). Generated by ciburn.</sub>"
    )
    return "\n".join(out) + "\n"


def _where(f: Finding) -> str:
    wf = (f.workflow or "").removeprefix(".github/workflows/")
    return f"{wf}#{f.job}" if f.job else wf or "(repo)"
